// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proxy/vless/database/config.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int64                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`                        // Время жизни кэша в секундах
	MaxSize       int32                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"` // Максимальный размер кэша
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSettings) Reset() {
	*x = CacheSettings{}
	mi := &file_proxy_vless_database_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSettings) ProtoMessage() {}

func (x *CacheSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_database_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSettings.ProtoReflect.Descriptor instead.
func (*CacheSettings) Descriptor() ([]byte, []int) {
	return file_proxy_vless_database_config_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSettings) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CacheSettings) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

type Settings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionString string                 `protobuf:"bytes,1,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	Table            string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Pool             int32                  `protobuf:"varint,3,opt,name=pool,proto3" json:"pool,omitempty"`
	Cache            *CacheSettings         `protobuf:"bytes,4,opt,name=cache,proto3" json:"cache,omitempty"` // Настройки кэширования
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_proxy_vless_database_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_database_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proxy_vless_database_config_proto_rawDescGZIP(), []int{1}
}

func (x *Settings) GetConnectionString() string {
	if x != nil {
		return x.ConnectionString
	}
	return ""
}

func (x *Settings) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Settings) GetPool() int32 {
	if x != nil {
		return x.Pool
	}
	return 0
}

func (x *Settings) GetCache() *CacheSettings {
	if x != nil {
		return x.Cache
	}
	return nil
}

type ClientsStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Settings      *Settings              `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientsStorage) Reset() {
	*x = ClientsStorage{}
	mi := &file_proxy_vless_database_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientsStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientsStorage) ProtoMessage() {}

func (x *ClientsStorage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_vless_database_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientsStorage.ProtoReflect.Descriptor instead.
func (*ClientsStorage) Descriptor() ([]byte, []int) {
	return file_proxy_vless_database_config_proto_rawDescGZIP(), []int{2}
}

func (x *ClientsStorage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientsStorage) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_proxy_vless_database_config_proto protoreflect.FileDescriptor

const file_proxy_vless_database_config_proto_rawDesc = "" +
	"\n" +
	"!proxy/vless/database/config.proto\x12\n" +
	"xray.proxy\"<\n" +
	"\rCacheSettings\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x03R\x03ttl\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x05R\amaxSize\"\x92\x01\n" +
	"\bSettings\x12+\n" +
	"\x11connection_string\x18\x01 \x01(\tR\x10connectionString\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x12\n" +
	"\x04pool\x18\x03 \x01(\x05R\x04pool\x12/\n" +
	"\x05cache\x18\x04 \x01(\v2\x19.xray.proxy.CacheSettingsR\x05cache\"V\n" +
	"\x0eClientsStorage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x120\n" +
	"\bsettings\x18\x02 \x01(\v2\x14.xray.proxy.SettingsR\bsettingsBO\n" +
	"\x0ecom.xray.proxyP\x01Z.github.com/xtls/xray-core/proxy/vless/database\xaa\x02\n" +
	"Xray.Proxyb\x06proto3"

var (
	file_proxy_vless_database_config_proto_rawDescOnce sync.Once
	file_proxy_vless_database_config_proto_rawDescData []byte
)

func file_proxy_vless_database_config_proto_rawDescGZIP() []byte {
	file_proxy_vless_database_config_proto_rawDescOnce.Do(func() {
		file_proxy_vless_database_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_vless_database_config_proto_rawDesc), len(file_proxy_vless_database_config_proto_rawDesc)))
	})
	return file_proxy_vless_database_config_proto_rawDescData
}

var file_proxy_vless_database_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_vless_database_config_proto_goTypes = []any{
	(*CacheSettings)(nil),  // 0: xray.proxy.CacheSettings
	(*Settings)(nil),       // 1: xray.proxy.Settings
	(*ClientsStorage)(nil), // 2: xray.proxy.ClientsStorage
}
var file_proxy_vless_database_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.Settings.cache:type_name -> xray.proxy.CacheSettings
	1, // 1: xray.proxy.ClientsStorage.settings:type_name -> xray.proxy.Settings
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_vless_database_config_proto_init() }
func file_proxy_vless_database_config_proto_init() {
	if File_proxy_vless_database_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_vless_database_config_proto_rawDesc), len(file_proxy_vless_database_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_vless_database_config_proto_goTypes,
		DependencyIndexes: file_proxy_vless_database_config_proto_depIdxs,
		MessageInfos:      file_proxy_vless_database_config_proto_msgTypes,
	}.Build()
	File_proxy_vless_database_config_proto = out.File
	file_proxy_vless_database_config_proto_goTypes = nil
	file_proxy_vless_database_config_proto_depIdxs = nil
}
