name: Build and Push to GHCR  

on:
  push:
    branches: 
      - "vless-db-validator"
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository code  
        uses: actions/checkout@v4

      - name: Set up Go 1.25.1  
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'
          cache: true

      - name: Run unit tests  
        run: |
          echo "🧪 Running unit tests..."
          go test -v -short ./...

      - name: Run database tests  
        run: |
          echo "🗄️ Running database tests..."
          go test -v ./proxy/vless/database/...

      - name: Run cache tests  
        run: |
          echo "⚡ Running cache tests..."
          go test -v ./proxy/vless/database/cache/...

      - name: Run validator tests  
        run: |
          echo "✅ Running validator tests..."
          go test -v ./proxy/vless/database/...

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry  
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata  
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Теги из названий веток (например, vless-db-validator)
            type=ref,event=branch
            # Семантические версии из git тегов (1.2.3 из v1.2.3)
            type=semver,pattern={{version}}
            #_major_.minor_ из семантических версий (1.2 из v1.2.3)
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image  
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

